// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: calculator/v1/calculator.proto

package calculatorv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/kostyay/otel-demo/controller/api/calculator/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// CalculatorServiceName is the fully-qualified name of the CalculatorService service.
	CalculatorServiceName = "calculator.v1.CalculatorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CalculatorServiceCalculateProcedure is the fully-qualified name of the CalculatorService's
	// Calculate RPC.
	CalculatorServiceCalculateProcedure = "/calculator.v1.CalculatorService/Calculate"
	// CalculatorServiceListProcedure is the fully-qualified name of the CalculatorService's List RPC.
	CalculatorServiceListProcedure = "/calculator.v1.CalculatorService/List"
	// CalculatorServiceGetProcedure is the fully-qualified name of the CalculatorService's Get RPC.
	CalculatorServiceGetProcedure = "/calculator.v1.CalculatorService/Get"
	// CalculatorServiceCleanupProcedure is the fully-qualified name of the CalculatorService's Cleanup
	// RPC.
	CalculatorServiceCleanupProcedure = "/calculator.v1.CalculatorService/Cleanup"
)

// CalculatorServiceClient is a client for the calculator.v1.CalculatorService service.
type CalculatorServiceClient interface {
	Calculate(context.Context, *connect_go.Request[v1.CalculateRequest]) (*connect_go.Response[v1.CalculateResponse], error)
	List(context.Context, *connect_go.Request[v1.ListRequest]) (*connect_go.Response[v1.ListResponse], error)
	Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error)
	Cleanup(context.Context, *connect_go.Request[v1.CleanupRequest]) (*connect_go.Response[v1.CleanupResponse], error)
}

// NewCalculatorServiceClient constructs a client for the calculator.v1.CalculatorService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCalculatorServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) CalculatorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &calculatorServiceClient{
		calculate: connect_go.NewClient[v1.CalculateRequest, v1.CalculateResponse](
			httpClient,
			baseURL+CalculatorServiceCalculateProcedure,
			opts...,
		),
		list: connect_go.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+CalculatorServiceListProcedure,
			opts...,
		),
		get: connect_go.NewClient[v1.GetRequest, v1.GetResponse](
			httpClient,
			baseURL+CalculatorServiceGetProcedure,
			opts...,
		),
		cleanup: connect_go.NewClient[v1.CleanupRequest, v1.CleanupResponse](
			httpClient,
			baseURL+CalculatorServiceCleanupProcedure,
			opts...,
		),
	}
}

// calculatorServiceClient implements CalculatorServiceClient.
type calculatorServiceClient struct {
	calculate *connect_go.Client[v1.CalculateRequest, v1.CalculateResponse]
	list      *connect_go.Client[v1.ListRequest, v1.ListResponse]
	get       *connect_go.Client[v1.GetRequest, v1.GetResponse]
	cleanup   *connect_go.Client[v1.CleanupRequest, v1.CleanupResponse]
}

// Calculate calls calculator.v1.CalculatorService.Calculate.
func (c *calculatorServiceClient) Calculate(ctx context.Context, req *connect_go.Request[v1.CalculateRequest]) (*connect_go.Response[v1.CalculateResponse], error) {
	return c.calculate.CallUnary(ctx, req)
}

// List calls calculator.v1.CalculatorService.List.
func (c *calculatorServiceClient) List(ctx context.Context, req *connect_go.Request[v1.ListRequest]) (*connect_go.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Get calls calculator.v1.CalculatorService.Get.
func (c *calculatorServiceClient) Get(ctx context.Context, req *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Cleanup calls calculator.v1.CalculatorService.Cleanup.
func (c *calculatorServiceClient) Cleanup(ctx context.Context, req *connect_go.Request[v1.CleanupRequest]) (*connect_go.Response[v1.CleanupResponse], error) {
	return c.cleanup.CallUnary(ctx, req)
}

// CalculatorServiceHandler is an implementation of the calculator.v1.CalculatorService service.
type CalculatorServiceHandler interface {
	Calculate(context.Context, *connect_go.Request[v1.CalculateRequest]) (*connect_go.Response[v1.CalculateResponse], error)
	List(context.Context, *connect_go.Request[v1.ListRequest]) (*connect_go.Response[v1.ListResponse], error)
	Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error)
	Cleanup(context.Context, *connect_go.Request[v1.CleanupRequest]) (*connect_go.Response[v1.CleanupResponse], error)
}

// NewCalculatorServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCalculatorServiceHandler(svc CalculatorServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(CalculatorServiceCalculateProcedure, connect_go.NewUnaryHandler(
		CalculatorServiceCalculateProcedure,
		svc.Calculate,
		opts...,
	))
	mux.Handle(CalculatorServiceListProcedure, connect_go.NewUnaryHandler(
		CalculatorServiceListProcedure,
		svc.List,
		opts...,
	))
	mux.Handle(CalculatorServiceGetProcedure, connect_go.NewUnaryHandler(
		CalculatorServiceGetProcedure,
		svc.Get,
		opts...,
	))
	mux.Handle(CalculatorServiceCleanupProcedure, connect_go.NewUnaryHandler(
		CalculatorServiceCleanupProcedure,
		svc.Cleanup,
		opts...,
	))
	return "/calculator.v1.CalculatorService/", mux
}

// UnimplementedCalculatorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCalculatorServiceHandler struct{}

func (UnimplementedCalculatorServiceHandler) Calculate(context.Context, *connect_go.Request[v1.CalculateRequest]) (*connect_go.Response[v1.CalculateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calculator.v1.CalculatorService.Calculate is not implemented"))
}

func (UnimplementedCalculatorServiceHandler) List(context.Context, *connect_go.Request[v1.ListRequest]) (*connect_go.Response[v1.ListResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calculator.v1.CalculatorService.List is not implemented"))
}

func (UnimplementedCalculatorServiceHandler) Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calculator.v1.CalculatorService.Get is not implemented"))
}

func (UnimplementedCalculatorServiceHandler) Cleanup(context.Context, *connect_go.Request[v1.CleanupRequest]) (*connect_go.Response[v1.CleanupResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calculator.v1.CalculatorService.Cleanup is not implemented"))
}
